### ISSUE TITLE
panic with chart generation

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#1030]
Here's a panic we got. It seems to be trying to make a slice with a negative number of elements. Not sure what caused it. Not repro'd yet.

```
0 unevaluated, 0 unknown
panic: runtime error: makeslice: len out of range [recovered]
panic: runtime error: makeslice: len out of range

goroutine 231 [running]:
text/template.errRecover(0xc329f8d760)
/usr/local/go/src/text/template/exec.go:100 +0xbc
bosun.org/_third_party/github.com/vdobler/chart.(*Range).fSetup(0xc369788f7=
8,
0xb, 0xd, 0x0, 0xfff0000000000000)
/go/src/bosun.org/_third_party/github.com/vdobler/chart/chart.go:580 +0x1294
bosun.org/_third_party/github.com/vdobler/chart.(*Range).Setup(0xc369788f78=
,
0xb, 0xd, 0x22e, 0xc, 0x1)
/go/src/bosun.org/_third_party/github.com/vdobler/chart/chart.go:622 +0x7b4
bosun.org/_third_party/github.com/vdobler/chart.(*ScatterChart).Plot(0xc369=
788d80,
0x7fed28193968, 0xc2de61e320)
/go/src/bosun.org/_third_party/github.com/vdobler/chart/scatter.go:142 +0x217
bosun.org/cmd/bosun/sched.(*Schedule).ExprSVG(0x1151f20, 0x0, 0x0,
0x7fedffdcb9b0, 0xc2d1a7c0e0, 0x320, 0x258, 0x0, 0x0, 0xc218bf6900, ...)
/go/src/bosun.org/cmd/bosun/sched/chart.go:54 +0x32a
bosun.org/cmd/bosun/sched.(*Context).graph(0xc25c29e900, 0x9d09a0,
0xc2e79520c0, 0x0, 0x0, 0x9c8501, 0x0, 0x0, 0x0, 0x0)
/go/src/bosun.org/cmd/bosun/sched/template.go:307 +0xc0a
bosun.org/cmd/bosun/sched.(*Context).Graph(0xc25c29e900, 0x9d09a0,
0xc2e79520c0, 0x115b208, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/bosun.org/cmd/bosun/sched/template.go:321 +0xb0
reflect.Value.call(0xbf6100, 0xc25c29e900, 0x1513, 0xc1f3f0, 0x4,
0xc36d7bd8c0, 0x2, 0x2, 0x0, 0x0, ...)
/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xbf6100, 0xc25c29e900, 0x1513, 0xc308f88180, 0x1, 0x1,
0x0, 0x0, 0x0)
/usr/local/go/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc25c29e940, 0xbf6100, 0xc25c29e900, 0x16,
0xbf6100, 0xc25c29e900, 0x1513, 0x7fedffdcb320, 0xc2081677a0, 0xc2081dd1a1,
...)
/usr/local/go/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalField(0xc25c29e940, 0xbf6100, 0xc25c29e900,
0x16, 0xc2081dd1a1, 0x5, 0x7fedffdcb320, 0xc2081677a0, 0xc208140a00, 0x2,
...)
/usr/local/go/src/text/template/exec.go:478 +0x34b
text/template.(*state).evalFieldChain(0xc25c29e940, 0xbf6100, 0xc25c29e900,
0x16, 0xbf6100, 0xc25c29e900, 0x16, 0x7fedffdcb320, 0xc2081677a0,
0xc208142600, ...)
/usr/local/go/src/text/template/exec.go:449 +0x2ad
text/template.(*state).evalFieldNode(0xc25c29e940, 0xbf6100, 0xc25c29e900,
0x16, 0xc2081677a0, 0xc208140a00, 0x2, 0x2, 0x0, 0x0, ...)
/usr/local/go/src/text/template/exec.go:416 +0x1e6
text/template.(*state).evalCommand(0xc25c29e940, 0xbf6100, 0xc25c29e900,
0x16, 0xc208167770, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/usr/local/go/src/text/template/exec.go:354 +0xb39
text/template.(*state).evalPipeline(0xc25c29e940, 0xbf6100, 0xc25c29e900,
0x16, 0xc208174410, 0x0, 0x0, 0x0)
/usr/local/go/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walk(0xc25c29e940, 0xbf6100, 0xc25c29e900, 0x16,
0x7fedffdcb368, 0xc20822a330)
/usr/local/go/src/text/template/exec.go:167 +0x145
text/template.(*state).walk(0xc25c29e940, 0xbf6100, 0xc25c29e900, 0x16,
0x7fedac660fa8, 0xc208167710)
/usr/local/go/src/text/template/exec.go:175 +0x862
text/template.(*state).walkIfOrWith(0xc25c29e940, 0xa, 0xbf6100,
0xc25c29e900, 0x16, 0xc208218500, 0xc208167710, 0x0)
/usr/local/go/src/text/template/exec.go:205 +0x33e
text/template.(*state).walk(0xc25c29e940, 0xbf6100, 0xc25c29e900, 0x16,
0x7fedffdcbd58, 0xc20822c140)
/usr/local/go/src/text/template/exec.go:172 +0x616
text/template.(*state).walk(0xc25c29e940, 0xbf6100, 0xc25c29e900, 0x16,
0x7fedac660fa8, 0xc20822a240)
/usr/local/go/src/text/template/exec.go:175 +0x862
text/template.(*state).walkIfOrWith(0xc25c29e940, 0xa, 0xbf6100,
0xc25c29e900, 0x16, 0xc2082184b0, 0xc20822a240, 0xc208173d10)
/usr/local/go/src/text/template/exec.go:205 +0x33e
text/template.(*state).walk(0xc25c29e940, 0xbf6100, 0xc25c29e900, 0x16,
0x7fedffdcbd58, 0xc20822c280)
/usr/local/go/src/text/template/exec.go:172 +0x616
text/template.(*state).walk(0xc25c29e940, 0xbf6100, 0xc25c29e900, 0x16,
0x7fedac660fa8, 0xc208167680)
/usr/local/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc20822c000, 0x7fedffdcb9b0,
0xc2f61c1b20, 0xbf6100, 0xc25c29e900, 0x0, 0x0)
/usr/local/go/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).Execute(0xc208173920, 0x7fedffdcb9b0,
0xc2f61c1b20, 0xbf6100, 0xc25c29e900, 0x0, 0x0)
/usr/local/go/src/html/template/template.go:78 +0xa3
bosun.org/cmd/bosun/sched.(*Schedule).ExecuteBody(0x1151f20, 0xc29e801500,
0xc208274420, 0xc290e42ff0, 0xc208056800, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/bosun.org/cmd/bosun/sched/template.go:109 +0x226
bosun.org/cmd/bosun/sched.(*Schedule).RunHistory(0x1151f20, 0xc29e801500)
/go/src/bosun.org/cmd/bosun/sched/check.go:143 +0xa95
bosun.org/cmd/bosun/sched.(*Schedule).Check(0x1151f20, 0x0, 0x0,
0xeccffe40f, 0x275a0ac8, 0x1151ba0, 0x19a16644cc, 0x0, 0x0)
/go/src/bosun.org/cmd/bosun/sched/check.go:356 +0x364
bosun.org/cmd/bosun/sched.(*Schedule).Run(0x1151f20, 0x0, 0x0)
/go/src/bosun.org/cmd/bosun/sched/sched.go:426 +0x2f7
bosun.org/cmd/bosun/sched.Run(0x0, 0x0)
/go/src/bosun.org/cmd/bosun/sched/sched.go:367 +0x3c
main.func=C2=B7004()
/go/src/bosun.org/cmd/bosun/main.go:134 +0x32
created by main.main
/go/src/bosun.org/cmd/bosun/main.go:136 +0xd90
```

**Comment by PhilippWendler** [comment]
I have the same problem.

For me it occurs when Bosun tries to generate a graph from a Graphite data source where some values are missing (because the host in question was added only recently, so values for the past are not present). My expression is the following:

    $graph = graphite("aliasSub(consolidateBy(collectd.*.df-*.percent_bytes-used, 'max'), 'df-', '/')", "7d", "", ".host.disk")

In the template I have

    {{.Graph .Alert.Vars.graph "%"}}

In the rule editor, Bosun reports `runtime error: makeslice: len out of range` and the generated template contains the following in the body:

    There was a runtime error processing alert disk.full{host=ate_fim_uni-passau_de} using the disk.full template. The following errors occurred:
    Body: runtime error: makeslice: len out of range
    Use this link to the rule page to correct this.

If I put this query and the graph in the config file, bosun immediately crashes with a similar stack trace:
```
2015/09/04 16:04:56 check alert disk.full done (197.891078ms): 1 crits, 1 warns, 0 unevaluated, 0 unknown
panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range

goroutine 33 [running]:
text/template.errRecover(0xc20829d750)
        /usr/src/go/src/text/template/exec.go:100 +0xbc
bosun.org/_third_party/github.com/vdobler/chart.(*Range).fSetup(0xc2081f2c00, 0xb, 0xd, 0x0, 0xfff0000000000000)
        /go/src/bosun.org/_third_party/github.com/vdobler/chart/chart.go:597 +0x1294
bosun.org/_third_party/github.com/vdobler/chart.(*Range).Setup(0xc2081f2c00, 0xb, 0xd, 0x22e, 0xc, 0x1)
        /go/src/bosun.org/_third_party/github.com/vdobler/chart/chart.go:639 +0x7b4
bosun.org/_third_party/github.com/vdobler/chart.(*ScatterChart).Plot(0xc2081f2a00, 0x7ff45f2b6bb0, 0xc208285e00)
        /go/src/bosun.org/_third_party/github.com/vdobler/chart/scatter.go:142 +0x217
bosun.org/cmd/bosun/sched.(*Schedule).ExprSVG(0x1199040, 0x0, 0x0, 0x7ff45f2a1ad0, 0xc20825fc70, 0x320, 0x258, 0xc20800fa9b, 0x1, 0xc208794400, ...)
        /go/src/bosun.org/cmd/bosun/sched/chart.go:54 +0x32a
bosun.org/cmd/bosun/sched.(*Context).graph(0xc2080f55c0, 0x9d8000, 0xc208261b90, 0xc20800fa9b, 0x1, 0x9cfb01, 0x0, 0x0, 0x0, 0x0)
        /go/src/bosun.org/cmd/bosun/sched/template.go:324 +0xdf1
bosun.org/cmd/bosun/sched.(*Context).Graph(0xc2080f55c0, 0x9d8000, 0xc208261b90, 0xc208261bb0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/src/bosun.org/cmd/bosun/sched/template.go:339 +0xb0
reflect.Value.call(0xc01d00, 0xc2080f55c0, 0x1513, 0xc27370, 0x4, 0xc2081ad8f0, 0x2, 0x2, 0x0, 0x0, ...)
        /usr/src/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xc01d00, 0xc2080f55c0, 0x1513, 0xc2081ad890, 0x2, 0x2, 0x0, 0x0, 0x0)
        /usr/src/go/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc2080f5880, 0xc01d00, 0xc2080f55c0, 0x16, 0xc01d00, 0xc2080f55c0, 0x1513, 0x7ff45f2a14b8, 0xc208158150, 0xc20800fa82, ...)
        /usr/src/go/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalField(0xc2080f5880, 0xc01d00, 0xc2080f55c0, 0x16, 0xc20800fa82, 0x5, 0x7ff45f2a14b8, 0xc208158150, 0xc208156bc0, 0x3, ...)
        /usr/src/go/src/text/template/exec.go:478 +0x34b
text/template.(*state).evalFieldChain(0xc2080f5880, 0xc01d00, 0xc2080f55c0, 0x16, 0xc01d00, 0xc2080f55c0, 0x16, 0x7ff45f2a14b8, 0xc208158150, 0xc208134d20, ...)
        /usr/src/go/src/text/template/exec.go:449 +0x2ad
text/template.(*state).evalFieldNode(0xc2080f5880, 0xc01d00, 0xc2080f55c0, 0x16, 0xc208158150, 0xc208156bc0, 0x3, 0x4, 0x0, 0x0, ...)
        /usr/src/go/src/text/template/exec.go:416 +0x1e6
text/template.(*state).evalCommand(0xc2080f5880, 0xc01d00, 0xc2080f55c0, 0x16, 0xc208158120, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/go/src/text/template/exec.go:354 +0xb39
text/template.(*state).evalPipeline(0xc2080f5880, 0xc01d00, 0xc2080f55c0, 0x16, 0xc208142d20, 0x0, 0x0, 0x0)
        /usr/src/go/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walk(0xc2080f5880, 0xc01d00, 0xc2080f55c0, 0x16, 0x7ff45f2a1500, 0xc208158210)
        /usr/src/go/src/text/template/exec.go:167 +0x145
text/template.(*state).walk(0xc2080f5880, 0xc01d00, 0xc2080f55c0, 0x16, 0x7ff45f2a8fc8, 0xc2081553e0)
        /usr/src/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc208156400, 0x7ff45f2a1ad0, 0xc208281f10, 0xc01d00, 0xc2080f55c0, 0x0, 0x0)
        /usr/src/go/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).Execute(0xc208155380, 0x7ff45f2a1ad0, 0xc208281f10, 0xc01d00, 0xc2080f55c0, 0x0, 0x0)
html/template.(*Template).Execute(0xc208155380, 0x7ff45f2a1ad0, 0xc208281f10, 0xc01d00, 0xc2080f55c0, 0x0, 0x0)
        /usr/src/go/src/html/template/template.go:78 +0xa3
bosun.org/cmd/bosun/sched.(*Schedule).ExecuteBody(0x1199040, 0xc2080a5570, 0xc20815a180, 0xc2081e1500, 0xc208145200, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/bosun.org/cmd/bosun/sched/template.go:124 +0x226
bosun.org/cmd/bosun/sched.(*Schedule).RunHistory(0x1199040, 0xc2080a5570)
        /go/src/bosun.org/cmd/bosun/sched/check.go:145 +0xaa8
bosun.org/cmd/bosun/sched.(*Schedule).Check(0x1199040, 0x0, 0x0, 0xecd7b9c08, 0x1905c639, 0x1198c20, 0x0, 0x0, 0x0, 0x0)
        /go/src/bosun.org/cmd/bosun/sched/check.go:378 +0x334
bosun.org/cmd/bosun/sched.(*Schedule).Run(0x1199040, 0x0, 0x0)
        /go/src/bosun.org/cmd/bosun/sched/sched.go:459 +0x2b2
bosun.org/cmd/bosun/sched.Run(0x0, 0x0)
        /go/src/bosun.org/cmd/bosun/sched/sched.go:403 +0x3c
main.func·004()
        /go/src/bosun.org/cmd/bosun/main.go:128 +0x32
created by main.main
        /go/src/bosun.org/cmd/bosun/main.go:130 +0xd24

goroutine 1 [select (no cases)]:
main.main()
        /go/src/bosun.org/cmd/bosun/main.go:155 +0xed9

goroutine 13 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 28 [sleep]:
bosun.org/metadata.collectMetadata()
        /go/src/bosun.org/metadata/metadata.go:184 +0x38
created by bosun.org/metadata.Init
        /go/src/bosun.org/metadata/metadata.go:177 +0xcc

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc20809fcd0, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20809fcd0, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20809fc70, 0x0, 0x7ff45f2a0cc8, 0xc2081e9550)
        /usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20813c570, 0x47e1f4, 0x0, 0x0)
        /usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20813c570, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2081dcde0, 0x7ff45f2a36c8, 0xc20813c570, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2081dcde0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc25350, 0x5, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1808 +0xba
bosun.org/cmd/bosun/web.Listen(0xc25350, 0x5, 0x9c0701, 0x0, 0x0, 0x0, 0x0)
        /go/src/bosun.org/cmd/bosun/web/web.go:121 +0x138f
main.func·003()
        /go/src/bosun.org/cmd/bosun/main.go:125 +0x6e
created by main.main
        /go/src/bosun.org/cmd/bosun/main.go:125 +0xd13

goroutine 34 [chan receive]:
main.func·006()
        /go/src/bosun.org/cmd/bosun/main.go:135 +0x129
created by main.main
        /go/src/bosun.org/cmd/bosun/main.go:148 +0xd35

goroutine 35 [select]:
bosun.org/cmd/bosun/sched.(*Schedule).Poll(0x1199040)
        /go/src/bosun.org/cmd/bosun/sched/notify.go:23 +0x111
created by bosun.org/cmd/bosun/sched.(*Schedule).Run
        /go/src/bosun.org/cmd/bosun/sched/sched.go:453 +0x134

goroutine 49 [syscall, locked to thread]:
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
```

I use Bosun 0.3. A workaround was to omit the graph from the template. To me this definitely looks like a bug.

**Comment by kylebrandt** [comment]
Might still be an issue but we wrap chart generation in recover, so closing this since it doesn't crash bosun. Can be reopened if still a significant issue for anyone

**Comment by Dieterbe** [comment]
also seeing these errors. but not the stacktraces above posters were sharing.
we use `bosun version 0.5.0-rc3-dev`
is it possible that these panics stop notifications to be triggered?
we're having some issues with critical events appearing in the bosun UI but the notification handler don't seem to be invoked, could this be an explanation?
```
2016/09/04 06:25:54 info: alertRunner.go:55: runHistory on cpu.idle took 139.096598ms
2016/09/04 06:25:54 error: template.go:292: panic rendering graphruntime error: makeslice: len out of range
2016/09/04 06:25:54 info: alertRunner.go:55: runHistory on grafana_alerting_jobqueue_preamqp took 71.105321ms
2016/09/04 06:25:54 info: check.go:537: check alert cassandra_writes done (999.296291ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
2016/09/04 06:25:54 info: alertRunner.go:55: runHistory on normalized_load took 243.366144ms
2016/09/04 06:25:54 info: alertRunner.go:55: runHistory on cassandra_writes took 63.981361ms
2016/09/04 06:25:54 error: template.go:292: panic rendering graphruntime error: makeslice: len out of range
2016/09/04 06:25:54 info: check.go:537: check alert metrictank_write_queue done (1.084476407s): 1 crits, 0 warns, 0 unevaluated, 0 unknown
```
