### ISSUE TITLE
armv5/6/7 build of scollector panics on synology DS2015xs

### ISSUE THREAD

**Issue by PeterGrace** [bosun-monitor/bosun#1116]
I was attempting to run scollector on our Synology nas devices to help track some disk-related i/o questions.  When I tried to run the 0.2.0 tagged releases of armv7, v6, v5 on the Synology, all three panic.  The Synology is a Linux system underneath of the DSM management interface, so there should be nothing preventing the use of scollector on this platform.

System info
=============
```nyhq-vdinas01> uname -a
Linux nyhq-vdinas01 3.2.40 #5565 SMP Mon Jun 8 16:45:09 CST 2015 armv7l GNU/Linux synology_alpine_ds2015xs```

Execution of armv7 binary yields:
====
```go
unexpected fault address 0x39a31c
fatal error: fault
[signal 0xb code=0x2 addr=0x39a31c pc=0x39a31c]

goroutine 1 [running, locked to thread]:
runtime.gothrow(0x498d88, 0x5)
        /usr/src/go/src/runtime/panic.go:503 +0x84 fp=0x1091b694 sp=0x1091b688
runtime.sigpanic()
        /usr/src/go/src/runtime/sigpanic_unix.go:29 +0x2a4 fp=0x1091b6bc sp=0x1091b694
crypto/sha512.init()
        ?:0 fp=0x1091b6c0 sp=0x1091b6c0
crypto/tls.init()
        /usr/src/go/src/crypto/tls/tls.go:275 +0xa8 fp=0x1091b6e0 sp=0x1091b6c0
crypto/tls.init()
        /usr/src/go/src/crypto/tls/tls.go:275 +0xa8 fp=0x1091b700 sp=0x1091b6e0
net/http.init()
        /usr/src/go/src/net/http/transport.go:1275 +0x6c fp=0x1091b784 sp=0x1091b700

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/src/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/src/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/src/go/src/runtime/malloc.go:712
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4
```

Execution of armv6 binary yields:
====
```go
unexpected fault address 0x39a380
fatal error: fault
[signal 0xb code=0x2 addr=0x39a380 pc=0x39a380]

goroutine 1 [running, locked to thread]:
runtime.gothrow(0x498d88, 0x5)
        /usr/src/go/src/runtime/panic.go:503 +0x84 fp=0x1091b694 sp=0x1091b688
runtime.sigpanic()
        /usr/src/go/src/runtime/sigpanic_unix.go:29 +0x2a4 fp=0x1091b6bc sp=0x1091b694
crypto/sha512.init()
        ?:0 fp=0x1091b6c0 sp=0x1091b6c0
crypto/tls.init()
        /usr/src/go/src/crypto/tls/tls.go:275 +0xa8 fp=0x1091b6e0 sp=0x1091b6c0
crypto/tls.init()
        /usr/src/go/src/crypto/tls/tls.go:275 +0xa8 fp=0x1091b700 sp=0x1091b6e0
net/http.init()
        /usr/src/go/src/net/http/transport.go:1275 +0x6c fp=0x1091b784 sp=0x1091b700

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/src/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/src/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/src/go/src/runtime/malloc.go:712
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4
```

Execution of armv5 binary yields:
====
```go
unexpected fault address 0x39aad8
fatal error: fault
[signal 0xb code=0x2 addr=0x39aad8 pc=0x39aad8]

goroutine 1 [running, locked to thread]:
runtime.gothrow(0x498d88, 0x5)
        /usr/src/go/src/runtime/panic.go:503 +0x84 fp=0x1091b694 sp=0x1091b688
runtime.sigpanic()
        /usr/src/go/src/runtime/sigpanic_unix.go:29 +0x2a4 fp=0x1091b6bc sp=0x1091b694
crypto/sha512.init()
        ?:0 fp=0x1091b6c0 sp=0x1091b6c0
crypto/tls.init()
        /usr/src/go/src/crypto/tls/tls.go:275 +0xa8 fp=0x1091b6e0 sp=0x1091b6c0
crypto/tls.init()
        /usr/src/go/src/crypto/tls/tls.go:275 +0xa8 fp=0x1091b700 sp=0x1091b6e0
net/http.init()
        /usr/src/go/src/net/http/transport.go:1275 +0x6c fp=0x1091b784 sp=0x1091b700

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/src/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/src/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/src/go/src/runtime/malloc.go:712
runtime.goexit()
        /usr/src/go/src/runtime/asm_arm.s:1322 +0x4
```

**Comment by gbrayut** [comment]
according to https://github.com/golang/go/wiki/GoArm it requires an EABI kernel:

> You must be running a EABI kernel. These are generally known as armel for softfloat (compatible with ARMv5) or armhf for hardware floating point (ARMv6 and above).

http://forum.synology.com/wiki/index.php/What_kind_of_CPU_does_my_NAS_have shows the ds2015xs is using an Annapurna Alpine AL514 armv7l CPU, but I can't find details about the kernel type.

**Comment by gbrayut** [comment]
http://chrisnelson.ca/2015/01/10/fixing-crashplan-on-synology-after-the-3-7-0-update-synology-repairing-upgrade-in-varpackagescrashplantargetupgrade1388728800370/ seems to indicate Annapurna Alpine AL514 has armhf support, but I haven't found how to confirm armhf or EABI is enabled in the kernel.

**Comment by PeterGrace** [comment]
It appears that as far as the synology is concerned, it is armhf...

```nyhq-vdinas01> ls -l /lib/ld-linux-armhf.so.3
lrwxrwxrwx    1 root     root            10 Jun 10 09:32 /lib/ld-linux-armhf.so.3 -> ld-2.17.so
```

**Comment by PeterGrace** [comment]
Crosscompiling go and then attempting to run the crosscompiled binary on the Synology also fails.

How it was compiled
=========
`GOOS=linux GOARCH=arm GOARM=7  CGO_ENABLED=0 ./make.bash`

Resultant panic from go when run on synology
========
```go
nyhq-vdinas01> ./go.v7
unexpected fault address 0x302550
fatal error: fault
[signal 0xb code=0x2 addr=0x302550 pc=0x302550]

goroutine 1 [running, locked to thread]:
runtime.gothrow(0x3aee30, 0x5)
        /home/pgrace/repo/golang/src/runtime/panic.go:503 +0x84 fp=0x10756e54 sp=0x10756e48
runtime.sigpanic()
        /home/pgrace/repo/golang/src/runtime/sigpanic_unix.go:29 +0x2a4 fp=0x10756e7c sp=0x10756e54
crypto/sha512.init()
        ?:0 fp=0x10756e80 sp=0x10756e80
crypto/tls.init()
        /home/pgrace/repo/golang/src/crypto/tls/tls.go:275 +0xa8 fp=0x10756ea0 sp=0x10756e80
crypto/tls.init()
        /home/pgrace/repo/golang/src/crypto/tls/tls.go:275 +0xa8 fp=0x10756ec0 sp=0x10756ea0
net/http.init()
        /home/pgrace/repo/golang/src/net/http/transport.go:1275 +0x6c fp=0x10756f44 sp=0x10756ec0

goroutine 2 [runnable]:
runtime.forcegchelper()
        /home/pgrace/repo/golang/src/runtime/proc.go:90
runtime.goexit()
        /home/pgrace/repo/golang/src/runtime/asm_arm.s:1322 +0x4

goroutine 3 [runnable]:
runtime.bgsweep()
        /home/pgrace/repo/golang/src/runtime/mgc0.go:82
runtime.goexit()
        /home/pgrace/repo/golang/src/runtime/asm_arm.s:1322 +0x4

goroutine 4 [runnable]:
runtime.runfinq()
        /home/pgrace/repo/golang/src/runtime/malloc.go:712
runtime.goexit()
        /home/pgrace/repo/golang/src/runtime/asm_arm.s:1322 +0x4

goroutine 5 [runnable]:
os/signal.loop()
        /home/pgrace/repo/golang/src/os/signal/signal_unix.go:19
created by os/signal.init·1
        /home/pgrace/repo/golang/src/os/signal/signal_unix.go:27 +0x40
```

**Comment by mjibson** [comment]
This is unfortunate, but unlikely to change, so am closing.
