### ISSUE TITLE
Bosun dashboard http: panic invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1229]
Right now every time I request the bosun dashboard I get an "Unable to fetch alerts" error with the 502 bad gateway from haproxy. Checking the logs I see this:

```
Jul 31 23:40:23 ny-bosun01 bosun[45030]: 2015/07/31 23:40:23 check took 58.200522ms
Jul 31 23:41:23 ny-bosun01 bosun[45030]: 2015/07/31 23:41:23 starting check
Jul 31 23:41:23 ny-bosun01 bosun[45030]: 2015/07/31 23:41:23 check alert host.down start
Jul 31 23:41:24 ny-bosun01 bosun[45030]: 2015/07/31 23:41:24 check alert host.down done (765.795813ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
Jul 31 23:41:24 ny-bosun01 bosun[45030]: 2015/07/31 23:41:24 check alert os.low.memory start
Jul 31 23:41:24 ny-bosun01 bosun[45030]: 2015/07/31 23:41:24 check alert os.low.memory done (301.167441ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
Jul 31 23:41:24 ny-bosun01 bosun[45030]: 2015/07/31 23:41:24 check alert os.net.drop_err start
Jul 31 23:41:27 ny-bosun01 bosun[45030]: 2015/07/31 23:41:27 check alert os.net.drop_err done (3.540835208s): 0 crits, 0 warns, 2 unevaluated, 0 unknown
Jul 31 23:41:27 ny-bosun01 bosun[45030]: 2015/07/31 23:41:27 check alert os.diskspace start
Jul 31 23:41:52 ny-bosun01 bosun[45030]: 2015/07/31 23:41:52 http: panic serving 10.8.0.48:53481: runtime error: invalid memory address or nil pointer dereference#012goroutine 861620 [running]:#012net/http.func·011()#012#011/usr/local/go/src/net/http/server.go:1130 +0xbb#012bosun.org/cmd/bosun/sched.func·027(0x7fb70f199238, 0xc2cf0fbf80)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/sched/sched.go:363 +0x77e#012bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Timing).Step(0xc2cf0fbda0, 0xc46db0, 0x6, 0xc378bfca40)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/types.go:214 +0x17a#012bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc3650d3950, 0xc46db0, 0x6, 0xc378bfca40)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/types.go:193 +0x55#012bosun.org/cmd/bosun/sched.(*Schedule).MarshalGroups(0x11aa100, 0x7fb72e5c0850, 0xc3650d3950, 0xc30ed13f30, 0x0, 0xc37b599900, 0x0, 0x0)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/sched/sched.go:381 +0x511#012bosun.org/cmd/bosun/web.Alerts(0x7fb72e5c0850, 0xc3650d3950, 0x7fb72e5c0de0, 0xc318f18460, 0xc2218d8c30, 0x0, 0x0, 0x0, 0x0)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/web/web.go:337 +0xad#012bosun.org/cmd/bosun/web.func·021(0x7fb72e5c0850, 0xc3650d3950, 0x7fb72e5c0de0, 0xc318f18460, 0xc2218d8c30)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/web/web.go:230 +0x71#012bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ProfileRequest(0xc28db38760, 0xc3650d3950, 0x7fb72e5c0de0, 0xc318f18460, 0xc2218d8c30)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:287 +0xe2#012bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ServeH
Jul 31 23:41:52 ny-bosun01 bosun[45030]: 2015/07/31 23:41:52 http: panic serving 10.8.0.48:53480: runtime error: invalid memory address or nil pointer dereference#012goroutine 861320 [running]:#012net/http.func·011()#012#011/usr/local/go/src/net/http/server.go:1130 +0xbb#012bosun.org/cmd/bosun/sched.func·027(0x7fb70f199238, 0xc2d0c46a80)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/sched/sched.go:363 +0x77e#012bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Timing).Step(0xc2d0c46900, 0xc46db0, 0x6, 0xc3c3d239a0)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/types.go:214 +0x17a#012bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc3650d3a70, 0xc46db0, 0x6, 0xc3c3d239a0)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/types.go:193 +0x55#012bosun.org/cmd/bosun/sched.(*Schedule).MarshalGroups(0x11aa100, 0x7fb72e5c0850, 0xc3650d3a70, 0xc3c3d22d90, 0x0, 0xc3473d7900, 0x0, 0x0)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/sched/sched.go:381 +0x511#012bosun.org/cmd/bosun/web.Alerts(0x7fb72e5c0850, 0xc3650d3a70, 0x7fb72e5c0de0, 0xc318f18500, 0xc2d37fb520, 0x0, 0x0, 0x0, 0x0)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/web/web.go:337 +0xad#012bosun.org/cmd/bosun/web.func·021(0x7fb72e5c0850, 0xc3650d3a70, 0x7fb72e5c0de0, 0xc318f18500, 0xc2d37fb520)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/web/web.go:230 +0x71#012bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ProfileRequest(0xc28db38760, 0xc3650d3a70, 0x7fb72e5c0de0, 0xc318f18500, 0xc2d37fb520)#012#011/home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:287 +0xe2#012bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ServeH
```

I tried incognito mode and had the same issue. Waited a few minutes and tried again and it started working.

**Comment by captncraig** [comment]
should be fixed by #1232
