### ISSUE TITLE
bosun died with a 'SIGABRT'

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1309]
Might be a Go bug?

```
2015/09/09 17:34:05 info: check.go:428: check alert haproxy.hits_by_top start
2015/09/09 17:34:05 info: check.go:449: check alert haproxy.hits_by_top done (312.714193ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
2015/09/09 17:34:05 info: alertRunner.go:56: runHistory on haproxy.hits_by_top took 12.552717ms
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x3ca7a32625 m=27

goroutine 0 [idle]:

goroutine 1 [select (no cases), 1096 minutes]:
main.main()
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/cmd/bosun/main.go:172 +0xdd3

goroutine 17 [syscall, 1097 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 6 [syscall, 1097 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 11397948 [IO wait]:
net.runtime_pollWait(0x7f9699868a00, 0x72, 0xc82000e160)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc9e612e4c0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc9e612e4c0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc9e612e460, 0xcabbc1a400, 0x200, 0x200, 0x0, 0x7f977978f050, 0xc82000e160)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
```

**Comment by gbrayut** [comment]
May be related to https://github.com/golang/go/issues/12233

**Comment by gbrayut** [comment]
I didnt see any issues with system cpu/memory, bosun's goroutine count, or linux.proc.* for memory/fds/etc leading up to the outage. Example (from co-bosun) http://goo.gl/bx9m5M

**Comment by gbrayut** [comment]
Yeah... might be a bug in Go 1.5. Stack trace at https://github.com/golang/go/issues/12233#issuecomment-133106542 looks very similar to the above.

**Comment by gbrayut** [comment]
Full crash log at https://dl.dropboxusercontent.com/u/21013682/Issues/bosun.pthread_create_SIGABRT.log

**Comment by gbrayut** [comment]
There is a workaround that appears to prevent this issue according to https://github.com/golang/go/issues/12233#issuecomment-143357529

Changes in go 1.5.2 should also prevent this when it is released
