### ISSUE TITLE
Crashes when trying to use the influx query type

### ISSUE THREAD

**Issue by berset** [bosun-monitor/bosun#1418]
When I try to test the following alert, it seems like I only get unhelpful crashes. 
I'm using version v0.4.0
Since the influxUsername and influxPassword options does not exist in this version, that could be a source of the error (my influxdb requires auth).
## alert

```
alert mypod.memory {
    template = influx
    $metric = avg(influx("k8s",'''SELECT value FROM memory/usage_bytes_gauge WHERE container_name =~ /k8s_mypod/ GROUP BY container_name''', "5m", ""))
    crit = $metric > 700
    warn = $metric > 500
}
```
## logs

```
2015/10/26 14:15:58 http: panic serving 192.168.99.1:64842: runtime error: index out of range
goroutine 136 [running]:
net/http.(*conn).serve.func1(0xc8206a4790, 0x7fb313f43298, 0xc820022888)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
bosun.org/cmd/bosun/conf.errRecover(0xc82012d250)
    /go/src/bosun.org/cmd/bosun/conf/conf.go:185 +0xbb
bosun.org/cmd/bosun/expr/parse.(*Tree).recover(0xc820338850, 0xc82012c940)
    /go/src/bosun.org/cmd/bosun/expr/parse/parse.go:191 +0x8d
bosun.org/cmd/bosun/expr.influxTag(0xc820386200, 0x4, 0x4, 0xc820338850, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/expr/influx.go:28 +0x224
bosun.org/cmd/bosun/expr/parse.(*FuncNode).Tags(0xc820323c80, 0x1, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/expr/parse/node.go:137 +0x73
bosun.org/cmd/bosun/expr.tagFirst(0xc820389db0, 0x1, 0x1, 0xf91803, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/expr/funcs.go:44 +0x47
bosun.org/cmd/bosun/expr/parse.(*FuncNode).Tags(0xc820323c00, 0xc820338850, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/expr/parse/node.go:137 +0x73
bosun.org/cmd/bosun/expr/parse.(*BinaryNode).Check(0xc820356de0, 0xc820338850, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/expr/parse/node.go:275 +0x3ce
bosun.org/cmd/bosun/expr/parse.(*Tree).parse(0xc820338850)
    /go/src/bosun.org/cmd/bosun/expr/parse/parse.go:243 +0xb5
bosun.org/cmd/bosun/expr/parse.(*Tree).Parse(0xc820338850, 0xc8203734d0, 0x8d, 0xc820389d90, 0x2, 0x2, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/expr/parse/parse.go:233 +0xdf
bosun.org/cmd/bosun/expr/parse.Parse(0xc8203734d0, 0x8d, 0xc820389d90, 0x2, 0x2, 0xc820338850, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/expr/parse/parse.go:113 +0x9c
bosun.org/cmd/bosun/expr.New(0xc8203734d0, 0x8d, 0xc820389d90, 0x2, 0x2, 0x40fb66, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/expr/expr.go:67 +0xac
bosun.org/cmd/bosun/conf.(*Conf).NewExpr(0xc820112900, 0xc8203734d0, 0x8d, 0x4)
    /go/src/bosun.org/cmd/bosun/conf/conf.go:1125 +0xc2
bosun.org/cmd/bosun/conf.(*Conf).loadAlert(0xc820112900, 0xc8203d9700)
    /go/src/bosun.org/cmd/bosun/conf/conf.go:820 +0x1379
bosun.org/cmd/bosun/conf.(*Conf).loadSection(0xc820112900, 0xc8203d9700)
    /go/src/bosun.org/cmd/bosun/conf/conf.go:513 +0xeb
bosun.org/cmd/bosun/conf.New(0xdffb70, 0xb, 0xc82031d800, 0x7f9, 0xc820112900, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/conf/conf.go:368 +0xf7f
bosun.org/cmd/bosun/web.buildConfig(0xc82069d340, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/web/expr.go:437 +0x160
bosun.org/cmd/bosun/web.Rule(0x7fb313f42e10, 0xc820372cf0, 0x7fb313f4f390, 0xc8206a48f0, 0xc82069d340, 0x0, 0x0, 0x0, 0x0)
    /go/src/bosun.org/cmd/bosun/web/expr.go:296 +0x46a
bosun.org/cmd/bosun/web.JSON.func1(0x7fb313f42e10, 0xc820372cf0, 0x7fb313f4f390, 0xc8206a48f0, 0xc82069d340)
    /go/src/bosun.org/cmd/bosun/web/web.go:232 +0x6b
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ProfileRequest(0xc8202fe310, 0xc820372cf0, 0x7fb313f4f390, 0xc8206a48f0, 0xc82069d340)
    /go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:287 +0xdf
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ServeHTTP(0xc8202fe310, 0x0, 0x7fb313f4f390, 0xc8206a48f0, 0xc82069d340)
    /go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:281 +0xba
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Handler).ServeHTTP(0xc8202fe320, 0x7fb313f4f390, 0xc8206a48f0, 0xc82069d340)
    <autogenerated>:9 +0xb6
bosun.org/_third_party/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820270cd0, 0x7fb313f4f390, 0xc8206a48f0, 0xc82069d340)
    /go/src/bosun.org/_third_party/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc8200508d0, 0x7fb313f4f390, 0xc8206a48f0, 0xc82069d340)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc8203126c0, 0x7fb313f4f390, 0xc8206a48f0, 0xc82069d340)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8206a4790)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by berset** [comment]
I have now tested with the following version:

```
$ git describe --tags
0.4.0-119-gdda36ed
```

And the auth settings, I still get an error: "2015/10/27 12:15:40 error: check.go:578: influx: did not get a valid result from InfluxDB"

If I do the same query in the InfluxDB admin console, I get a seemingly ok result.

**Comment by gbrayut** [comment]
I think the issue is you are trying to use a groupByInterval but don't have any aggregation functions. The "60m", "", "2m" in your query would cause Bosun to generate the following query and result:

```
SELECT value FROM "memory/usage_bytes_gauge" WHERE container_name =~ /k8s_mypod/ AND time > (now() - 60m) GROUP BY container_name, time(2m)

Result:
Server returned error: error parsing query: GROUP BY requires at least one aggregate function
```

According to the [InfluxDB documentation](https://influxdb.com/docs/v0.9/query_language/data_exploration.html#the-group-by-clause) you need to use an aggregate function and include a where clause when using GROUP BY time, so you can either change the end of your query to "60m", "", "" to exclude the time grouping or use an aggregation function like mean(value):

```
Bosun Expression:
influx("k8s",'''SELECT mean(value) FROM "memory/usage_bytes_gauge" WHERE container_name =~ /k8s_mypod/" group by host''',"60m","","2m")

Influx Query Generated:
SELECT mean(value) FROM "memory/usage_bytes_gauge" WHERE container_name =~ /k8s_mypod/ AND time > (now() - 60m) GROUP BY container_name, time(2m)
```

Which should generate a valid time series similar to this:

![image](https://cloud.githubusercontent.com/assets/304401/10769846/bf5c7102-7cad-11e5-94fd-42b66e60ec1b.png)

I highly recommend testing your queries using the expression tab prior to creating your alert. We should probably expose a way to see the influxdb query that is being generated, as right now it can be difficult to troubleshoot why a query is failing.

**Comment by berset** [comment]
Could the influxdb version be part of the problem?

I have now tried adjusting my query to this:
```
influx("k8s",'''SELECT max(value) FROM "memory/usage_bytes_gauge" WHERE container_name =~ /k8s_mypod/''',"60m","","2m")
```

It still results in `influx: did not get a valid result from InfluxDB` when I try it in the expression tab.

If I expand the query like you showed, and run it in the influxdb admin console it works ..

**Comment by berset** [comment]
This does indeed seem to be the case: 

Your request seems to follow:
https://influxdb.com/docs/v0.9/guides/querying_data.html

But mine is:

```
# influxdb -v       
InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
```

It would be really nice if you could support the different influxdb versions, like grafana etc ..

**Comment by gbrayut** [comment]
Unfortunately I believe v0.9 is required, as tags were added in v0.9 according to https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md#features-31

The Go InfluxQL parser is also a v0.9 feature, so supporting v0.8 is unlikely to happen.

Sorry if that wasn't clear and for the generic error messages. I'll look at updating our docs with the v0.9 requirements.
