### ISSUE TITLE
Can't run scollector on windows on command line

### ISSUE THREAD

**Issue by eswdd** [bosun-monitor/bosun#1509]
Hi,

Trying to run the latest windows binary (amd64) on Windows 2008r2 Server. We can install and run as a service, but trying to run on the command line fails when running as a local admin user:

```
PS C:\Users\user\desktop> .\scollector-windows-amd64.exe -p
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
bosun.org/_third_party/code.google.com/p/winsvc/svc.IsAnInteractiveSession(0x0, 0x0, 0x0)
/go/src/bosun.org/_third_party/code.google.com/p/winsvc/svc/security.go:82 +0x393
main.win_service_main()
/go/src/bosun.org/cmd/scollector/service_windows.go:35 +0xa9
main.main()
/go/src/bosun.org/cmd/scollector/main.go:127 +0x227

goroutine 2 [runnable]:
runtime.forcegchelper()
/usr/src/go/src/runtime/proc.go:90
runtime.goexit()
/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
/usr/src/go/src/runtime/mgc0.go:82
runtime.goexit()
/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
/usr/src/go/src/runtime/malloc.go:712
runtime.goexit()
/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
os/signal.loop()
/usr/src/go/src/os/signal/signal_unix.go:19
created by os/signal.init-�1
/usr/src/go/src/os/signal/signal_unix.go:27 +0x3c

goroutine 6 [runnable]:
bosun.org/_third_party/github.com/mjibson/snmp.func-�003()
/go/src/bosun.org/_third_party/github.com/mjibson/snmp/snmp.go:417
created by bosun.org/_third_party/github.com/mjibson/snmp.init-�1
/go/src/bosun.org/_third_party/github.com/mjibson/snmp/snmp.go:421 +0x73

goroutine 7 [runnable]:
bosun.org/cmd/scollector/collectors.func-�001()
/go/src/bosun.org/cmd/scollector/collectors/collectors.go:71
created by bosun.org/cmd/scollector/collectors.init-�1
/go/src/bosun.org/cmd/scollector/collectors/collectors.go:77 +0x2c
PS C:\Users\user\desktop>
```

Any ideas on what we're doing wrong?

**Comment by eswdd** [comment]
Turns out we're running an ancient version - closing.
