### ISSUE TITLE
graphite alert breaks when log() is used.

### ISSUE THREAD

**Issue by dsummersl** [bosun-monitor/bosun#1608]
When I try to use `log()` in my graphite query it crashes bosun.

Example:

```
alert broken.graphite {
	$w = graphite("log(bunyan.*.*:sumrate)", "15m", "5m", ".level.environment")
    $q = avg($w)
    warn = $q > 10
}
```

The following traces appear in the bosun error logs:
```
2016/02/19 20:35:46 info: check.go:544: check alert broken.graphite done (2.444059848s): 0 crits, 0 warns, 0 unevaluated, 0 unknown
panic: opentsdb: bad tag:  10)

goroutine 58 [running]:
bosun.org/models.AlertKey.Group(0xc820a1df40, 0x4a, 0x187a240)
        /go/src/bosun.org/models/alertKey.go:46 +0x286
bosun.org/cmd/bosun/sched.NewStatus(0xc820a1df40, 0x4a, 0x4a)
        /go/src/bosun.org/cmd/bosun/sched/check.go:42 +0x2f
bosun.org/cmd/bosun/sched.(*Schedule).runHistory(0x187a240, 0xc821100b40, 0xc820a1df40, 0x4a, 0xc82029aac0, 0xc820819410, 0x0)
        /go/src/bosun.org/cmd/bosun/sched/check.go:131 +0xb6
bosun.org/cmd/bosun/sched.(*Schedule).RunHistory(0x187a240, 0xc821100b40)
        /go/src/bosun.org/cmd/bosun/sched/check.go:115 +0xe8
bosun.org/cmd/bosun/sched.(*Schedule).checkAlert(0x187a240, 0xc8200e8c00)
        /go/src/bosun.org/cmd/bosun/sched/alertRunner.go:55 +0xec
bosun.org/cmd/bosun/sched.(*Schedule).RunAlert(0x187a240, 0xc8200e8c00)
        /go/src/bosun.org/cmd/bosun/sched/alertRunner.go:42 +0x5f
created by bosun.org/cmd/bosun/sched.(*Schedule).Run
        /go/src/bosun.org/cmd/bosun/sched/alertRunner.go:25 +0x1f4

goroutine 1 [select (no cases)]:
main.main()
        /go/src/bosun.org/cmd/bosun/main.go:172 +0xdd3

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 35 [select]:
bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc8200594a0)
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x7c8
created by bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x9a5

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 37 [select]:
bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc8200594a0)
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x1a2
created by bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x9e9


goroutine 36 [select]:
bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc8200594a0)
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x253
created by bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x9c7

goroutine 9 [select]:
bosun.org/_third_party/github.com/siddontang/go/log.(*Logger).run(0xc82004b3b0)
        /go/src/bosun.org/_third_party/github.com/siddontang/go/log/log.go:100 +0x269
created by bosun.org/_third_party/github.com/siddontang/go/log.New
        /go/src/bosun.org/_third_party/github.com/siddontang/go/log/log.go:80 +0x1cc

goroutine 34 [select]:
bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc8200594a0)
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14b
created by bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7a1

goroutine 33 [select]:
bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc8200594a0)
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x54a
created by bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/bosun.org/_third_party/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x77f

goroutine 27 [sleep]:
time.Sleep(0xdf8475800)
        /usr/local/go/src/runtime/time.go:59 +0xf9
bosun.org/metadata.collectMetadata()
        /go/src/bosun.org/metadata/metadata.go:197 +0x35
created by bosun.org/metadata.Init
        /go/src/bosun.org/metadata/metadata.go:190 +0xc1
```

**Comment by dsummersl** [comment]
I can execute the graphite() block in the expressions tab...
