### ISSUE TITLE
Crash if config doesn't list OpenTSDB

### ISSUE THREAD

**Issue by mkuzmin** [bosun-monitor/bosun#1627]
I'm trying to setup Bosun with InfluxDB.
My `dev.conf` is just a single line:
```
influxHost=influx-host:8083
```
At opening dashboard Bosun crashes with 
```
2016/02/29 04:16:19 http: panic serving [::1]:55715: runtime error: invalid memory address or nil pointer dereference
goroutine 61 [running]:
net/http.(*conn).serve.func1(0xc8202cca80)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xdc5720, 0xc8200100e0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
bosun.org/cmd/bosun/web.OpenTSDBVersion(0x1d6eb78, 0xc8203e01b0, 0x1d6eb18, 0xc820160f70, 0xc820184620, 0x0, 0x0, 0x0, 0x0)
	/go/src/bosun.org/cmd/bosun/web/web.go:349 +0x8e
bosun.org/cmd/bosun/web.JSON.func1(0x1d6eb78, 0xc8203e01b0, 0x1d6eb18, 0xc820160f70, 0xc820184620)
	/go/src/bosun.org/cmd/bosun/web/web.go:264 +0x6b
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.Handler.ProfileRequest(0xc820259b30, 0xc8203e01b0, 0x1d6eb18, 0xc820160f70, 0xc820184620)
	/go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:287 +0xdf
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.Handler.ServeHTTP(0xc820259b30, 0x0, 0x1d6eb18, 0xc820160f70, 0xc820184620)
	/go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:281 +0xba
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Handler).ServeHTTP(0xc820259b40, 0x1d6eb18, 0xc820160f70, 0xc820184620)
	<autogenerated>:9 +0xb6
bosun.org/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820159a40, 0x1d6eb18, 0xc820160f70, 0xc820184620)
	/go/src/bosun.org/vendor/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820068a80, 0x1d6eb18, 0xc820160f70, 0xc820184620)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820187e00, 0x1d6eb18, 0xc820160f70, 0xc820184620)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8202cca80)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

Looks like some of OpenTSDB settings are mandatory. 

Version 0.5.0-rc1-dev, just built from sources.
Full log at https://gist.github.com/mkuzmin/1990d22fe7d7656e3bf2

**Comment by kylebrandt** [comment]
Can you see if fixed in https://github.com/bosun-monitor/bosun/tree/fixVersionPanic ?

**Comment by mkuzmin** [comment]
Yes, that helps. 
Thank you for the rapid response!
