### ISSUE TITLE
Unable to execute escount query

### ISSUE THREAD

**Issue by JozoVilcek** [bosun-monitor/bosun#1733]
I am trying to make `escount` query work on bosun `0.5.0-rc2` with no luck. I seek wisdom and help on what's wrong.

My dummy expression:
```
$index = esdaily("@timestamp", "logstash-", "2006.01.02")
escount($index, "type", esall(), "1m", "1h", "")
```
Using mini profiler I got an elastic REST query which works. Error I got from bosun is:

```
2016/05/13 12:50:08 info: expr.go:131: invalid character '<' looking for beginning of value: goroutine 53 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
bosun.org/cmd/bosun/expr.errRecover(0xc820227008)
        /go/src/bosun.org/cmd/bosun/expr/expr.go:131 +0x53
panic(0x11750c0, 0xc820126900)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
bosun.org/cmd/bosun/expr.(*State).walkFunc.func1(0x7fdc899310d0, 0xc82006f380)
        /go/src/bosun.org/cmd/bosun/expr/expr.go:695 +0xa72
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Timing).Step(0xc82006f320, 0xc82039d080, 0xd, 0xc820435f60)
        /go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:214 +0x15c
bosun.org/cmd/bosun/expr.(*State).walkFunc(0xc820140d20, 0xc82023ab40, 0x7fdc899310d0, 0xc82006f320, 0x5)
        /go/src/bosun.org/cmd/bosun/expr/expr.go:703 +0x125
bosun.org/cmd/bosun/expr.(*State).walk(0xc820140d20, 0x7fdc89931048, 0xc82023ab40, 0x7fdc899310d0, 0xc82006f320, 0x7fdc899310d0)
        /go/src/bosun.org/cmd/bosun/expr/expr.go:449 +0x125
bosun.org/cmd/bosun/expr.(*Expr).ExecuteState.func1(0x7fdc899310d0, 0xc82006f320)
        /go/src/bosun.org/cmd/bosun/expr/expr.go:120 +0x65
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Timing).Step(0xc82006f1a0, 0x140daa0, 0xc, 0xc820435f40)
        /go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:214 +0x15c
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc82023aab0, 0x140daa0, 0xc, 0xc820435f40)
        /go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:193 +0x52
bosun.org/cmd/bosun/expr.(*Expr).ExecuteState(0xc820888270, 0xc820140d20, 0x7fdc89930f70, 0xc82023aab0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/bosun.org/cmd/bosun/expr/expr.go:121 +0x19c
bosun.org/cmd/bosun/expr.(*Expr).Execute(0xc820888270, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8201356c0, 0x1, ...)
        /go/src/bosun.org/cmd/bosun/expr/expr.go:109 +0x2cd
bosun.org/cmd/bosun/web.Expr(0x7fdc89930f70, 0xc82023aab0, 0x7fdc89930e18, 0xc82022c9c0, 0xc82025e620, 0x0, 0x0, 0x0, 0x0)
        /go/src/bosun.org/cmd/bosun/web/expr.go:80 +0x74c
bosun.org/cmd/bosun/web.JSON.func1(0x7fdc89930f70, 0xc82023aab0, 0x7fdc89930e18, 0xc82022c9c0, 0xc82025e620)
        /go/src/bosun.org/cmd/bosun/web/web.go:264 +0x6b
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.Handler.ProfileRequest(0xc82011ae30, 0xc82023aab0, 0x7fdc89930e18, 0xc82022c9c0, 0xc82025e620)
        /go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:287 +0xdf
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.Handler.ServeHTTP(0xc82011ae30, 0x0, 0x7fdc89930e18, 0xc82022c9c0, 0xc82025e620)
        /go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:281 +0xba
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Handler).ServeHTTP(0xc82011ae40, 0x7fdc89930e18, 0xc82022c9c0, 0xc82025e620)
        <autogenerated>:9 +0xb6
bosun.org/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820130690, 0x7fdc89930e18, 0xc82022c9c0, 0xc82025e620)
        /go/src/bosun.org/vendor/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc82000ab40, 0x7fdc89930e18, 0xc82022c9c0, 0xc82025e620)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820146000, 0x7fdc89930e18, 0xc82022c9c0, 0xc82025e620)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820146080)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by kylebrandt** [comment]
Can you try master? That exact expression works okay for me.

**Comment by kylebrandt** [comment]
Also, es* family funcs require elastic 2.0 or later, are you using that?

**Comment by JozoVilcek** [comment]
Yes, master works for me. `0.5.0-rc1` and `0.5.0-rc2` does not.
