### ISSUE TITLE
Alert on elasticsearch query crashes

### ISSUE THREAD

**Issue by JozoVilcek** [bosun-monitor/bosun#1748]
Bosun crashes when I test an alert on elasticsearch query. Visualization of a query in expression tab works fine. This happens only when I group over a field containing arbitrary text. This way I am trying to get a warning alert over non-numeric event.

```
panic: opentsdb: bad tag: -expected-4-parts

goroutine 306 [running]:
panic(0x1197760, 0xc820f20580)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
bosun.org/models.AlertKey.Group(0xc820867c00, 0x3e1, 0xc820867c00)
        /go/src/bosun.org/models/alertKey.go:46 +0x286
bosun.org/cmd/bosun/sched.NewIncident(0xc820867c00, 0x3e1, 0x0)
        /go/src/bosun.org/cmd/bosun/sched/check.go:46 +0x11d
bosun.org/cmd/bosun/web.procRule(0x7fdb03bee258, 0xc821058ba0, 0xc820215c00, 0xc820358180, 0xeced550f9, 0xc800000000, 0x1d34220, 0x0, 0xc8203f69f6, 0x0, ...)
        /go/src/bosun.org/cmd/bosun/web/expr.go:180 +0xa65
bosun.org/cmd/bosun/web.Rule.func1.1(0x7fdb03bee258, 0xc821058ba0)
        /go/src/bosun.org/cmd/bosun/web/expr.go:320 +0x252
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Timing).Step(0xc821058900, 0xc820f3cf60, 0xa, 0xc821058b40)
        /go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:214 +0x15c
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc8203f6a20, 0xc820f3cf60, 0xa, 0xc821058b40)
        /go/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:193 +0x52
bosun.org/cmd/bosun/web.Rule.func1()
        /go/src/bosun.org/cmd/bosun/web/expr.go:323 +0x362
created by bosun.org/cmd/bosun/web.Rule
        /go/src/bosun.org/cmd/bosun/web/expr.go:328 +0x78c
```

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/commit/235b72502edf6cbe871eb7c63be7986933d7d98b

Need to do same for elastic I imagine.

**Comment by Alex-Hou** [comment]
@kylebrandt Got the same panic with Prometheus Datasource while doing `findUnknownAlerts` check.
