### ISSUE TITLE
Crash if incorrect data in Silences

### ISSUE THREAD

**Issue by svagner** [bosun-monitor/bosun#2386]
# Problem
2019/02/08 12:00:22 error: silence.go:20: Error fetching silences.unexpected end of JSON input
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf4cc4b]

goroutine 38005 [running]:
bosun.org/cmd/bosun/sched.(*Schedule).CheckNotifications(0x2061760, 0x0, 0x0, 0x0)
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/sched/notify.go:68 +0x1cb
bosun.org/cmd/bosun/sched.(*Schedule).dispatchNotifications(0x2061760)
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/sched/notify.go:28 +0x1c0
created by bosun.org/cmd/bosun/sched.(*Schedule).Run
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/sched/alertRunner.go:18 +0xa4

# How to emulate
Key 5de2a7387b084908234906b89e522b7dcd6e8afc exists in SilencesByEnd and Silences. But key in Silences contain empty string

# Fix
https://github.com/bosun-monitor/bosun/pull/2385

**Comment by svagner** [comment]
Fix was merged
