### ISSUE TITLE
index out of range panic

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#633]
this rule
```
alert os.high.cpu.web {
template = generic
$cpu_per_host = avg(graphite("groupByNode(foo.*.cpu.*.cpu.idle,1,'avg')", "5m", "", "host"))
$q = $cpu_per_host
$number_of_hosts = len(t($cpu_per_host, ""))
$total_cpu = sum(t($cpu_per_host), "")
#Returns a series of 0/1 (True, False) above 50
$host_under_threshold = t($cpu_per_host < 50, "")
$number_under_threshold = sum($host_under_threshold)
$under_treshold = $number_under_threshold / $number_of_hosts

warn = ($under_treshold > 0.5) || ($total_cpu < 300)
crit = ($under_treshold > 0.8) || ($total_cpu < 200)
}
```
causes the following panic:
```
2015/01/06 14:59:20 http: panic serving [::1]:55109: runtime error: index out of range
goroutine 16921 [running]:
net/http.func·011()
	/usr/lib/go/src/net/http/server.go:1130 +0xbb
bosun.org/cmd/bosun/conf.errRecover(0xc2089d71a8)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:163 +0xbc
bosun.org/cmd/bosun/expr/parse.(*Tree).recover(0xc20826ccb0, 0xc2089d6a38)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/parse.go:177 +0x87
bosun.org/cmd/bosun/expr.tagTranspose(0xc208aa9640, 0x1, 0x1, 0xc20826d0a0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/funcs.go:47 +0x400
bosun.org/cmd/bosun/expr/parse.(*FuncNode).Tags(0xc2082520e0, 0xc208261d10, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/node.go:132 +0x79
bosun.org/cmd/bosun/expr.tagFirst(0xc208e04ea0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/funcs.go:42 +0x54
bosun.org/cmd/bosun/expr/parse.(*FuncNode).Tags(0xc20826df10, 0xc208261d10, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/node.go:132 +0x79
bosun.org/cmd/bosun/expr/parse.(*BinaryNode).Tags(0xc2086f5260, 0xc208261d10, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/node.go:291 +0x57
bosun.org/cmd/bosun/expr/parse.(*BinaryNode).Check(0xc2086f52c0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/node.go:256 +0xde
bosun.org/cmd/bosun/expr/parse.(*Tree).parse(0xc20826ccb0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/parse.go:230 +0xb5
bosun.org/cmd/bosun/expr/parse.(*Tree).Parse(0xc20826ccb0, 0xc20810adc0, 0x154, 0xc208aa9590, 0x2, 0x2, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/parse.go:220 +0xf0
bosun.org/cmd/bosun/expr/parse.Parse(0xc20810adc0, 0x154, 0xc208aa9590, 0x2, 0x2, 0xc20826ccb0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/parse.go:99 +0xbd
bosun.org/cmd/bosun/expr.New(0xc20810adc0, 0x154, 0xc208aa9590, 0x2, 0x2, 0x0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/expr.go:48 +0x11e
bosun.org/cmd/bosun/conf.(*Conf).NewExpr(0xc20c90e1a0, 0xc20810adc0, 0x154, 0x4, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:1118 +0xcf
bosun.org/cmd/bosun/conf.(*Conf).loadAlert(0xc20c90e1a0, 0xc209d077c0)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:752 +0x168e
bosun.org/cmd/bosun/conf.(*Conf).loadSection(0xc20c90e1a0, 0xc209d077c0)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:443 +0xd8
bosun.org/cmd/bosun/conf.New(0xa437b0, 0xb, 0xc20834c600, 0x58c, 0xc20c90e1a0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:340 +0xa14
bosun.org/cmd/bosun/web.Rule(0x7f6e39e9f0a8, 0xc2081be990, 0x7f6e39ea7260, 0xc208219ea0, 0xc2081deea0, 0x0, 0x0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/web/expr.go:241 +0x15e0
bosun.org/cmd/bosun/web.func·012(0x7f6e39e9f0a8, 0xc2081be990, 0x7f6e39ea7260, 0xc208219ea0, 0xc2081deea0)
	/home/dieter/go/src/bosun.org/cmd/bosun/web/web.go:194 +0x95
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ProfileRequest(0xc20820a1a0, 0xc2081be990, 0x7f6e39ea7260, 0xc208219ea0, 0xc2081deea0)
	/home/dieter/go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:287 +0xe2
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ServeHTTP(0xc20820a1a0, 0x0, 0x7f6e39ea7260, 0xc208219ea0, 0xc2081deea0)
	/home/dieter/go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:281 +0xc2
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Handler).ServeHTTP(0xc20820a1b0, 0x7f6e39ea7260, 0xc208219ea0, 0xc2081deea0)
	<autogenerated>:9 +0xbd
bosun.org/_third_party/github.com/gorilla/mux.(*Router).ServeHTTP(0xc208053090, 0x7f6e39ea7260, 0xc208219ea0, 0xc2081deea0)
	/home/dieter/go/src/bosun.org/_third_party/github.com/gorilla/mux/mux.go:98 +0x297
net/http.(*ServeMux).ServeHTTP(0xc20803c720, 0x7f6e39ea7260, 0xc208219ea0, 0xc2081deea0)
	/usr/lib/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208224120, 0x7f6e39ea7260, 0xc208219ea0, 0xc2081deea0)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20811b9a0)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e
2015/01/06 14:59:29 checkUnknown
2015/01/06 14:59:29 starting check
2015/01/06 14:59:29 checking alert os.high.cpu.web
2015/01/06 14:59:31 done checking alert os.high.cpu.web (1.271400677s): 5 crits, 7 warns
2015/01/06 14:59:32 http: panic serving [::1]:55114: runtime error: index out of range
goroutine 16985 [running]:
net/http.func·011()
	/usr/lib/go/src/net/http/server.go:1130 +0xbb
bosun.org/cmd/bosun/conf.errRecover(0xc2081d31a8)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:163 +0xbc
bosun.org/cmd/bosun/expr/parse.(*Tree).recover(0xc20819d500, 0xc2081d2a38)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/parse.go:177 +0x87
bosun.org/cmd/bosun/expr.tagTranspose(0xc208eaf0e0, 0x1, 0x1, 0xc20819d5e0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/funcs.go:47 +0x400
bosun.org/cmd/bosun/expr/parse.(*FuncNode).Tags(0xc20819d960, 0xc2081d4450, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/node.go:132 +0x79
bosun.org/cmd/bosun/expr.tagFirst(0xc2092da580, 0x2, 0x2, 0x0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/funcs.go:42 +0x54
bosun.org/cmd/bosun/expr/parse.(*FuncNode).Tags(0xc20819d8f0, 0xc2081d4450, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/node.go:132 +0x79
bosun.org/cmd/bosun/expr/parse.(*BinaryNode).Tags(0xc20963b440, 0xc2081d4450, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/node.go:291 +0x57
bosun.org/cmd/bosun/expr/parse.(*BinaryNode).Check(0xc20963b4a0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/node.go:256 +0xde
bosun.org/cmd/bosun/expr/parse.(*Tree).parse(0xc20819d500)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/parse.go:230 +0xb5
bosun.org/cmd/bosun/expr/parse.(*Tree).Parse(0xc20819d500, 0xc20880a000, 0x154, 0xc208eaefb0, 0x2, 0x2, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/parse.go:220 +0xf0
bosun.org/cmd/bosun/expr/parse.Parse(0xc20880a000, 0x154, 0xc208eaefb0, 0x2, 0x2, 0xc20819d500, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/parse/parse.go:99 +0xbd
bosun.org/cmd/bosun/expr.New(0xc20880a000, 0x154, 0xc208eaefb0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/expr/expr.go:48 +0x11e
bosun.org/cmd/bosun/conf.(*Conf).NewExpr(0xc2081c4000, 0xc20880a000, 0x154, 0x4, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:1118 +0xcf
bosun.org/cmd/bosun/conf.(*Conf).loadAlert(0xc2081c4000, 0xc20e88b1c0)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:752 +0x168e
bosun.org/cmd/bosun/conf.(*Conf).loadSection(0xc2081c4000, 0xc20e88b1c0)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:443 +0xd8
bosun.org/cmd/bosun/conf.New(0xa437b0, 0xb, 0xc208278000, 0x58c, 0xc2081c4000, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/conf/conf.go:340 +0xa14
bosun.org/cmd/bosun/web.Rule(0x7f6e39e9f0a8, 0xc20a7c62d0, 0x7f6e39ea7260, 0xc2081f6000, 0xc2081784e0, 0x0, 0x0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/web/expr.go:241 +0x15e0
bosun.org/cmd/bosun/web.func·012(0x7f6e39e9f0a8, 0xc20a7c62d0, 0x7f6e39ea7260, 0xc2081f6000, 0xc2081784e0)
	/home/dieter/go/src/bosun.org/cmd/bosun/web/web.go:194 +0x95
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ProfileRequest(0xc20820a1a0, 0xc20a7c62d0, 0x7f6e39ea7260, 0xc2081f6000, 0xc2081784e0)
	/home/dieter/go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:287 +0xe2
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ServeHTTP(0xc20820a1a0, 0x0, 0x7f6e39ea7260, 0xc2081f6000, 0xc2081784e0)
	/home/dieter/go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:281 +0xc2
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Handler).ServeHTTP(0xc20820a1b0, 0x7f6e39ea7260, 0xc2081f6000, 0xc2081784e0)
	<autogenerated>:9 +0xbd
bosun.org/_third_party/github.com/gorilla/mux.(*Router).ServeHTTP(0xc208053090, 0x7f6e39ea7260, 0xc2081f6000, 0xc2081784e0)
	/home/dieter/go/src/bosun.org/_third_party/github.com/gorilla/mux/mux.go:98 +0x297
net/http.(*ServeMux).ServeHTTP(0xc20803c720, 0x7f6e39ea7260, 0xc2081f6000, 0xc2081784e0)
	/usr/lib/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208224120, 0x7f6e39ea7260, 0xc2081f6000, 0xc2081784e0)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208351d60)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e
```
latest code from master.
Kyle was able to repro with the same alert with but with an opentsdb query:
```
template = test
$cpu_per_host = avg(q("sum:rate{counter,,1}:linux.cpu{host=ny-web*,type=idle}", "1h", ""))
$q = $cpu_per_host
$number_of_hosts = len(t($cpu_per_host, ""))
$total_cpu = sum(t($cpu_per_host), "")
#Returns a series of 0/1 (True, False) above 50
$host_under_threshold = t($cpu_per_host < 50, "")
$number_under_threshold = sum($host_under_threshold)
$under_treshold = $number_under_threshold / $number_of_hosts

warn = ($under_treshold > 0.5) || ($total_cpu < 300)
crit = ($under_treshold > 0.8) || ($total_cpu < 200)
}
```

**Comment by Dieterbe** [comment]
fixed in 58bc714d676c9b1421a585126da4922c4b9c87eb
