### ISSUE TITLE
some graphite responses result in "panic: opentsdb: bad tag: 0)" etc

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#710]
an expr like `graphite("groupByNode(transformNull(stats.*.upload_*,0),2,'sum')", "1h", "", "foo") > 0` results *sometimes* in:
```
panic: opentsdb: bad tag: 0)

goroutine 50 [running]:
bosun.org/cmd/bosun/expr.AlertKey.Group(0xc264862de0, 0x2d, 0x488ded1f4a1b1b36)
    /home/dieter/go/src/bosun.org/cmd/bosun/expr/alertkey.go:46 +0x271
bosun.org/cmd/bosun/sched.NewStatus(0xc264862de0, 0x2d, 0xc264862de0)
    /home/dieter/go/src/bosun.org/cmd/bosun/sched/check.go:18 +0x32
bosun.org/cmd/bosun/sched.(*Schedule).Status(0xf80900, 0xc264862de0, 0x2d, 0xc264862de0)
    /home/dieter/go/src/bosun.org/cmd/bosun/sched/check.go:30 +0x9b
bosun.org/cmd/bosun/sched.(*Schedule).CheckExpr(0xf80900, 0x0, 0x0, 0xc2647f2cc0, 0xc2081da0f0, 0xc2081aa1a8, 0x3, 0x0, 0x0, 0x0, ...)
    /home/dieter/go/src/bosun.org/cmd/bosun/sched/check.go:252 +0x7e2
bosun.org/cmd/bosun/sched.(*Schedule).CheckAlert(0xf80900, 0x0, 0x0, 0xc2647f2cc0, 0xc2081da0f0)
    /home/dieter/go/src/bosun.org/cmd/bosun/sched/check.go:202 +0x1d9
bosun.org/cmd/bosun/sched.(*Schedule).Check(0xf80900, 0x0, 0x0, 0xecc6d7be2, 0x17cb616b, 0xf80620, 0x420fea, 0x0, 0x0)
    /home/dieter/go/src/bosun.org/cmd/bosun/sched/check.go:73 +0x173
bosun.org/cmd/bosun/sched.(*Schedule).Run(0xf80900, 0x0, 0x0)
    /home/dieter/go/src/bosun.org/cmd/bosun/sched/sched.go:603 +0x31c
bosun.org/cmd/bosun/sched.Run(0x0, 0x0)
    /home/dieter/go/src/bosun.org/cmd/bosun/sched/sched.go:366 +0x3c
main.func·004()
    /home/dieter/go/src/bosun.org/cmd/bosun/main.go:113 +0x51
created by main.main
    /home/dieter/go/src/bosun.org/cmd/bosun/main.go:114 +0xc6a
```

this is because the graphite output series are bogusly labeled like `upload_free,0)`
i should be able to fairly easily track this down and fix it, by being more rigorous in parseGraphiteResponse probably. the problem is i can't reproduce this consistently, i'm often able to execute this expression without getting it to fail
![bug](https://cloud.githubusercontent.com/assets/20774/6151646/36147928-b1e5-11e4-9b0e-ae543de21dbf.png)
even when i clear the state file and rerun. once i can consistently reproduce it, i should be able to fix it.

**Comment by kylebrandt** [comment]
Assuming this was fixed by 1663 unless I hear otherwise

**Comment by Dieterbe** [comment]
yah #1663 probably !
