### ISSUE TITLE
Panic on Nil Results

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#713]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xfb2ee]

goroutine 51 [running]:
bosun.org/cmd/bosun/sched.(*Schedule).CheckExpr(0xb883c0, 0x0, 0x0, 0xc2083de0c0, 0xc2081a0000, 0xc20817c080, 0x2, 0x0, 0x0, 0x0, ...)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/check.go:262 +0xdbe
bosun.org/cmd/bosun/sched.(*Schedule).CheckAlert(0xb883c0, 0x0, 0x0, 0xc2083de0c0, 0xc2081a0000)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/check.go:224 +0x28a
bosun.org/cmd/bosun/sched.(*Schedule).Check(0xb883c0, 0x0, 0x0, 0xecc6eb970, 0xb58763e, 0xb88160, 0x0, 0x0, 0x0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/check.go:73 +0x173
bosun.org/cmd/bosun/sched.(*Schedule).Run(0xb883c0, 0x0, 0x0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:609 +0x386
bosun.org/cmd/bosun/sched.Run(0x0, 0x0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:366 +0x3c
main.func·004()
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:109 +0x1f
created by main.main
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:110 +0xc22

goroutine 1 [select (no cases)]:
main.main()
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:134 +0x12ed

goroutine 9 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 15 [chan receive]:
bosun.org/collect.queuer()
	/Users/kbrandt/src/bosun.org/collect/queue.go:16 +0x5e
created by bosun.org/collect.InitChan
	/Users/kbrandt/src/bosun.org/collect/collect.go:95 +0x324

goroutine 16 [sleep]:
bosun.org/collect.send()
	/Users/kbrandt/src/bosun.org/collect/queue.go:58 +0x296
created by bosun.org/collect.InitChan
	/Users/kbrandt/src/bosun.org/collect/collect.go:96 +0x335

goroutine 49 [sleep]:
bosun.org/collect.collect()
	/Users/kbrandt/src/bosun.org/collect/collect.go:282 +0x60d
created by bosun.org/collect.InitChan
	/Users/kbrandt/src/bosun.org/collect/collect.go:97 +0x346

goroutine 50 [IO wait]:
net.(*pollDesc).Wait(0xc2082b3f00, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2082b3f00, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2082b3ea0, 0x0, 0xcc4c60, 0xc20834d3d0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208432308, 0x82264, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208432308, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208408120, 0xcdd878, 0xc208432308, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208408120, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc208172038, 0x5, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1808 +0xba
bosun.org/cmd/bosun/web.Listen(0xc208172038, 0x5, 0x1, 0xc208174120, 0x13, 0x0, 0x0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/web/web.go:99 +0x14b0
main.func·003()
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:107 +0x6e
created by main.main
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:107 +0xc11

goroutine 52 [chan receive]:
main.func·005()
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:114 +0x3f
created by main.main
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:119 +0xd77

goroutine 53 [select]:
bosun.org/cmd/bosun/sched.(*Schedule).Poll(0xb883c0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/notify.go:21 +0x157
created by bosun.org/cmd/bosun/sched.(*Schedule).Run
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:591 +0xee

goroutine 54 [sleep]:
bosun.org/cmd/bosun/sched.func·027()
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:596 +0x37
created by bosun.org/cmd/bosun/sched.(*Schedule).Run
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:598 +0x144

goroutine 82 [IO wait]:
net.(*pollDesc).Wait(0xc20805c060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20805c060, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20805c000, 0xc20840c000, 0x1000, 0x1000, 0x0, 0xcc4c60, 0xc2083c60d8)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208432310, 0xc20840c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0xcdd8b0, 0xc208432310, 0xc2081d8058, 0xc20840c000, 0x1000, 0x1000, 0x5bd700, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2083b8180, 0xc20840c000, 0x1000, 0x1000, 0xc20808e900, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208408180)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208408180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2081d8000)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 83 [select]:
net/http.(*persistConn).writeLoop(0xc2081d8000)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:661 +0xcbc
exit status 2
[kbrandt@grove: ~/src/bosun.org/cmd/bosun]
[kbrandt@grove: ~/src/bosun.org/cmd/bosun] git diff
[kbrandt@grove: ~/src/bosun.org/cmd/bosun]
[kbrandt@grove: ~/src/bosun.org/cmd/bosun] git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
[kbrandt@grove: ~/src/bosun.org/cmd/bosun] go run main.go -c kdev.conf -dev
2015/02/12 10:11:07 RestoreState
2015/02/12 10:11:07 RestoreState done in 17.441676ms
2015/02/12 10:11:07 using local web assets
2015/02/12 10:11:07 bosun web listening on: :8070
2015/02/12 10:11:07 tsdb host: 192.168.59.103:4242
2015/02/12 10:11:22 starting check
2015/02/12 10:11:22 check alert darwin.high.cpu start
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xfb3be]

goroutine 52 [running]:
bosun.org/cmd/bosun/sched.(*Schedule).CheckExpr(0xb883e0, 0x0, 0x0, 0xc2083d62c0, 0xc208198000, 0xc20818e048, 0x2, 0x0, 0x0, 0x0, ...)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/check.go:262 +0xdbe
bosun.org/cmd/bosun/sched.(*Schedule).CheckAlert(0xb883e0, 0x0, 0x0, 0xc2083d62c0, 0xc208198000)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/check.go:224 +0x28a
bosun.org/cmd/bosun/sched.(*Schedule).Check(0xb883e0, 0x0, 0x0, 0xecc6eb99a, 0xc22f8ff8cb, 0xb88180, 0xc20838c040, 0x0, 0x0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/check.go:73 +0x173
bosun.org/cmd/bosun/sched.(*Schedule).Run(0xb883e0, 0x0, 0x0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:603 +0x31c
bosun.org/cmd/bosun/sched.Run(0x0, 0x0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:366 +0x3c
main.func·004()
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:113 +0x51
created by main.main
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:114 +0xc6a

goroutine 1 [select (no cases)]:
main.main()
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:138 +0x1335

goroutine 9 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 34 [IO wait]:
net.(*pollDesc).Wait(0xc20856e0d0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20856e0d0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20856e070, 0xc20800f000, 0x1000, 0x1000, 0x0, 0xcc4c60, 0xc208391390)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c0c0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0xce0358, 0xc20802c0c0, 0xc208088058, 0xc20800f000, 0x1000, 0x1000, 0xc2083ea100, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2083ce1c0, 0xc20800f000, 0x1000, 0x1000, 0xc2080aa000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20855a300)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20855a300, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208088000)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 19 [sleep]:
bosun.org/cmd/bosun/search.func·001()
	/Users/kbrandt/src/bosun.org/cmd/bosun/search/search.go:120 +0x36
created by bosun.org/cmd/bosun/search.(*Search).Index
	/Users/kbrandt/src/bosun.org/cmd/bosun/search/search.go:125 +0x148

goroutine 16 [chan receive]:
bosun.org/collect.queuer()
	/Users/kbrandt/src/bosun.org/collect/queue.go:16 +0x5e
created by bosun.org/collect.InitChan
	/Users/kbrandt/src/bosun.org/collect/collect.go:95 +0x324

goroutine 49 [sleep]:
bosun.org/collect.send()
	/Users/kbrandt/src/bosun.org/collect/queue.go:58 +0x296
created by bosun.org/collect.InitChan
	/Users/kbrandt/src/bosun.org/collect/collect.go:96 +0x335

goroutine 50 [sleep]:
bosun.org/collect.collect()
	/Users/kbrandt/src/bosun.org/collect/collect.go:282 +0x60d
created by bosun.org/collect.InitChan
	/Users/kbrandt/src/bosun.org/collect/collect.go:97 +0x346

goroutine 51 [IO wait]:
net.(*pollDesc).Wait(0xc208588bc0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208588bc0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208588b60, 0x0, 0xcc4c60, 0xc2083c8058)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c530, 0x8262e, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20802c530, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20856b500, 0xcddfc0, 0xc20802c530, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20856b500, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20802b828, 0x5, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1808 +0xba
bosun.org/cmd/bosun/web.Listen(0xc20802b828, 0x5, 0x746101, 0xc20801fa20, 0x13, 0x0, 0x0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/web/web.go:99 +0x14b0
main.func·003()
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:108 +0x6e
created by main.main
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:108 +0xc11

goroutine 53 [chan receive]:
main.func·005()
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:118 +0x3f
created by main.main
	/Users/kbrandt/src/bosun.org/cmd/bosun/main.go:123 +0xdbf

goroutine 81 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc208088000)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:661 +0xcbc

goroutine 67 [IO wait]:
net.(*pollDesc).Wait(0xc208560060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208560060, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208560000, 0xc208544000, 0x1000, 0x1000, 0x0, 0xcc4c60, 0xc2083912f0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20818a018, 0xc208544000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc2085760e8, 0xc208544000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2083c4000, 0xc208544000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208058060)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208058060, 0xc2086dbb0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208058060, 0x0, 0x0, 0x0, 0xc207fba100, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20845ec30, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20845ec30, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208058060, 0xc2084a3ee0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2085760a0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2085760a0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1751 +0x35e

goroutine 69 [IO wait]:
net.(*pollDesc).Wait(0xc208560140, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208560140, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2085600e0, 0xc2082f4000, 0x1000, 0x1000, 0x0, 0xcc4c60, 0xc2083a5b58)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20818a060, 0xc2082f4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0xce0358, 0xc20818a060, 0xc20807e1b8, 0xc2082f4000, 0x1000, 0x1000, 0x5bd6e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2083c4260, 0xc2082f4000, 0x1000, 0x1000, 0xc208015600, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208058840)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208058840, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20807e160)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 70 [select]:
net/http.(*persistConn).writeLoop(0xc20807e160)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:661 +0xcbc

goroutine 82 [select]:
bosun.org/cmd/bosun/sched.(*Schedule).Poll(0xb883e0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/notify.go:21 +0x157
created by bosun.org/cmd/bosun/sched.(*Schedule).Run
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:591 +0xc6

goroutine 83 [chan receive]:
bosun.org/cmd/bosun/sched.(*Schedule).CheckUnknown(0xb883e0)
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/check.go:192 +0xa4
created by bosun.org/cmd/bosun/sched.(*Schedule).Run
	/Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:592 +0xe3
exit status 2
```

Somehow it looks like Expr.Execute can return nil but not an error, and then results is nil so panic when trying to access results.Results

**Comment by kylebrandt** [comment]
It seems like it might happen when a check from the schedule runs an expression that has no corresponding metric in opentsdb.
