### ISSUE TITLE
http: panic serving [::1]:44847: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#878]
after compiling latest master (f279d83b01e5bc8de971ebadb6819249c1f722de ) and running with my prod bosun.conf (which has a bunch of notifications, templates, alerts, etc) on my laptop.
note that i loaded an alert from bosun.conf in the Rule page, changed it to a graphite query that would cause the graphite to return a 502 error (which it showed on the rule page), 
after that i went to the dashboard and saw:

```
$ ./bosun -dev -n -q -c /home/dieter/code/telemetry/bosun/bosun.conf
2015/04/08 14:00:09 RestoreState
2015/04/08 14:00:11 RestoreState done in 2.137878082s
2015/04/08 14:00:11 using local web assets
2015/04/08 14:00:11 bosun web listening on: :8070
2015/04/08 14:00:11 tsdb host: 
2015/04/08 14:00:19 wrote silence: 125.00B
2015/04/08 14:00:23 wrote status: 180.49MB
2015/04/08 14:00:23 wrote metadata: 3.59KB
2015/04/08 14:00:23 wrote metric: 68.00B
2015/04/08 14:00:23 wrote tagk: 42.00B
2015/04/08 14:00:23 wrote tagv: 68.00B
2015/04/08 14:00:24 wrote metrictags: 86.00B
2015/04/08 14:00:24 wrote notifications: 54.00B
2015/04/08 14:00:24 save to db complete
2015/04/08 14:00:29 graphite: 500 INTERNAL SERVER ERROR
2015/04/08 14:02:48 http: panic serving [::1]:44847: runtime error: invalid memory address or nil pointer dereference
goroutine 41 [running]:
net/http.func·011()
	/usr/lib/go/src/net/http/server.go:1130 +0xbb
bosun.org/cmd/bosun/sched.func·019(0x7f0528a95de8, 0xc2262e8180)
	/home/dieter/go/src/bosun.org/cmd/bosun/sched/sched.go:312 +0x75f
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Timing).Step(0xc2262e8060, 0xb923c0, 0x6, 0xc227d086c0)
	/home/dieter/go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/types.go:214 +0x17a
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc2261f2360, 0xb923c0, 0x6, 0xc227d086c0)
	/home/dieter/go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/types.go:193 +0x55
bosun.org/cmd/bosun/sched.(*Schedule).MarshalGroups(0x100fc80, 0x7f0528ada860, 0xc2261f2360, 0xc227d14070, 0x0, 0x0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/sched/sched.go:326 +0x487
bosun.org/cmd/bosun/web.Alerts(0x7f0528ada860, 0xc2261f2360, 0x7f0528ada800, 0xc22620e0a0, 0xc2262f6000, 0x0, 0x0, 0x0, 0x0)
	/home/dieter/go/src/bosun.org/cmd/bosun/web/web.go:322 +0xad
bosun.org/cmd/bosun/web.func·015(0x7f0528ada860, 0xc2261f2360, 0x7f0528ada800, 0xc22620e0a0, 0xc2262f6000)
	/home/dieter/go/src/bosun.org/cmd/bosun/web/web.go:198 +0x71
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ProfileRequest(0xc22621d270, 0xc2261f2360, 0x7f0528ada800, 0xc22620e0a0, 0xc2262f6000)
	/home/dieter/go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:287 +0xe2
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.Handler.ServeHTTP(0xc22621d270, 0x0, 0x7f0528ada800, 0xc22620e0a0, 0xc2262f6000)
	/home/dieter/go/src/bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler/miniprofiler.go:281 +0xc2
bosun.org/_third_party/github.com/MiniProfiler/go/miniprofiler.(*Handler).ServeHTTP(0xc22621d280, 0x7f0528ada800, 0xc22620e0a0, 0xc2262f6000)
	<autogenerated>:9 +0xbd
bosun.org/_third_party/github.com/gorilla/mux.(*Router).ServeHTTP(0xc208051220, 0x7f0528ada800, 0xc22620e0a0, 0xc2262f6000)
	/home/dieter/go/src/bosun.org/_third_party/github.com/gorilla/mux/mux.go:98 +0x297
net/http.(*ServeMux).ServeHTTP(0xc20803a6c0, 0x7f0528ada800, 0xc22620e0a0, 0xc2262f6000)
	/usr/lib/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc22626c300, 0x7f0528ada800, 0xc22620e0a0, 0xc2262f6000)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc22620e000)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e
```
the nilpointer is `                            Ago:      marshalTime(st.Last().Time),
`

**Comment by mjibson** [comment]
Since Last() returns a struct and not a pointer-to-a-struct, the npe couldn't have been do to Last(). It must instead be from st, which seems to be nil here. Thus, perhaps the grouping function is producing non-existent alert keys? This is strange.

**Comment by mjibson** [comment]
If this happens again please reopen.
